### ISSUE TITLE
Typo in Introduction to Making Figures with ggplot2

### ISSUE THREAD

**Issue by sherry3809** [sjspielman/datascience_for_biologists#3]
In the section Histograms, in the first gray box:
## Soecify the x-axis aesthetic

I believe you want       ## Specify the x-axis aesthetic.
Also, I you tubed and learned how to install tidy verse!

**Comment by sjspielman** [comment]
I believe installation instructions are in the intro too, right? Did I not include?

**Comment by sherry3809** [comment]
You did include

install.packages("tidyverse")
but I didn't know where to install it.

**Comment by sherry3809** [comment]
I thought I had responded.

 You did say install but did not say where to install.  I thought perhaps
this was obvious to others?

**Comment by sherry3809** [comment]
Just looked in Editor and found Install Packages under Tools

**Comment by sjspielman** [comment]
`install.packages("tidyverse")` is code for installing packages. That's it. There are other ways to do it, but this is how you code it. It does the whole install for you, so when you say "but I didn't know where to install it" you are overcomplicating things. If you run that line of code I provided, it will install to the correct location without issue.

**Comment by sherry3809** [comment]
thank you.
